# Generated by Django 5.0.2 on 2024-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(unique=True)),
                ('balance', models.FloatField(default=12100.09)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
