# Generated by Django 5.0.2 on 2024-06-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.IntegerField(null=True),
        ),
    ]
