# Generated by Django 5.0.2 on 2024-04-18 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountapp', '0002_initial'),
        ('addressapp', '0002_initial'),
        ('orderapp', '0001_initial'),
        ('productapp', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userprofile'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressapp.address'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.orderdetails'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.orderstatus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountapp.account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.orderdetails'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userprofile'),
        ),
    ]
