# Generated by Django 5.0.2 on 2024-04-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
