# Generated by Django 5.0.2 on 2024-06-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
